import assert from 'node:assert/strict'
import { createSave,startRun,setDraft,useHint,submitAnswer,advanceRun,getConceptStatus,getDueQuestions,reconcileQuestions,parseSave,isRpgAnswerCorrect } from '../src/lib/rpg/engine.ts'
const DAY=86400000, now=1800000000000
const q=(id,type='single')=>({id,hash:`h${id}`,familyId:id,conceptId:'c',contentVersion:'v1',track:'certification',examCode:'AIF-C01',courseCode:null,seriesSlug:null,topicSlug:null,domain:'D1',domainNumber:1,difficulty:1,type,questionStyle:'scenario',tags:[],concepts:[],stem:'Test',keyTerms:[],options:[{label:'A',text:'Alpha'},{label:'B',text:'Beta'}],correctAnswers:['A'],hint:'Hint',explanation:'Explanation',plainExplanation:null,optionAnalysis:null,whyOthersWrong:null,trap:null,mnemonic:null,references:null,relatedQuestionIds:[],sourceArticleUrl:null,sourceFile:'fixture',generatedBy:'human',reviewed:true,lang:'en'})
const questions=['a','b','c'].map(id=>q(id))
const play=(s,qs,time,hint=false,answer=['A'],quest='quest')=>{s=startRun(s,quest,qs,time);for(const question of qs){s=setDraft(s,answer);if(hint)s=useHint(s);s=submitAnswer(s,time);const once=s;s=submitAnswer(s,time);assert.equal(s,once,'duplicate submit');s=advanceRun(s,time)}return s}
let s=play(createSave('AIF-C01'),questions,now)
assert.equal(s.xp,50)
assert.equal(s.activeRun.victory,true)
assert.equal(getConceptStatus(s,'c',questions),'recall')
const repeat=play(s,questions,now+100)
assert.equal(repeat.xp,s.xp)
assert.deepEqual(repeat.reviews,s.reviews)
assert.equal(getDueQuestions(s,questions,now).length,0)
assert.equal(getDueQuestions(s,questions,now+DAY).length,3)
s=play(s,questions,now+DAY)
assert.equal(s.xp,65)
assert.equal(s.reviews.a.stage,1)
assert.equal(s.reviews.a.dueAt,now+4*DAY)
assert.equal(getConceptStatus(s,'c',questions),'mastered')
s=play(s,[questions[0]],now+DAY+100,false,['B'])
assert.equal(getConceptStatus(s,'c',questions),'reinforce')
assert.equal(s.reviews.a.dueAt,now+2*DAY+100)
s=play(s,[questions[1]],now+DAY+200)
assert.equal(getConceptStatus(s,'c',questions),'reinforce','another family success cannot clear unresolved failure')
s=play(s,[questions[0]],now+DAY+300,true)
assert.equal(getConceptStatus(s,'c',questions),'reinforce','hint-assisted correction cannot restore mastery')
s=play(s,[questions[0]],now+DAY+400)
assert.equal(getConceptStatus(s,'c',questions),'mastered','independent correction resolves failed family')
s=play(s,[questions[2]],now+DAY+500,true)
assert.equal(getConceptStatus(s,'c',questions),'reinforce','assisted answer after mastery needs reinforcement')
let hinted=play(createSave('AIF-C01'),questions,now,true)
assert.equal(hinted.xp,35)
assert.equal(getConceptStatus(hinted,'c',questions),'learning')
hinted=play(hinted,questions,now+DAY,true)
assert.equal(hinted.xp,35)
assert.equal(hinted.reviews.a.stage,0)
const newer=questions.map(q=>({...q,contentVersion:'v2',hash:'changed'}))
s=reconcileQuestions(s,newer,now+2*DAY)
assert.equal(getConceptStatus(s,'c',newer),'unexplored')
assert.equal(s.reviews.a.dueAt,now+2*DAY)
assert.equal(isRpgAnswerCorrect({...q('x','multi'),correctAnswers:['A','B']},['A','A']),false)
assert.equal(isRpgAnswerCorrect({...q('x','multi'),correctAnswers:['A','B']},['B','A']),true)
assert.equal(isRpgAnswerCorrect({...q('x','ordering'),correctAnswers:['A','B']},['B','A']),false)
assert.equal(isRpgAnswerCorrect({...q('x','matching'),correctAnswers:['A:1','B:2']},['B:2','A:1']),true)
let pending=startRun(createSave('AIF-C01'),'q',questions,now)
pending=useHint(setDraft(pending,['B']))
assert.deepEqual(parseSave(JSON.stringify(pending),'AIF-C01'),pending)
assert.deepEqual(parseSave(JSON.stringify(s),'AIF-C01'),s)
assert.throws(()=>parseSave('{"__proto__":{}}','AIF-C01'))
assert.throws(()=>parseSave(JSON.stringify({...s,examCode:'OTHER'}),'AIF-C01'))
assert.throws(()=>parseSave(JSON.stringify({...s,reviews:{a:{stage:-1}}}),'AIF-C01'))
assert.throws(()=>parseSave(JSON.stringify({...pending,activeRun:{...pending.activeRun,index:99}}),'AIF-C01'))
assert.throws(()=>parseSave(JSON.stringify({...pending,activeRun:{...pending.activeRun,questions:[{}]}}),'AIF-C01'))
assert.equal(play(createSave('AIF-C01'),questions,now,false,['B']).activeRun.victory,false)
assert.equal(startRun(pending,'other',questions,now),pending)
const five = ['a','b','c','d','e'].map(id=>q(id))
let threshold = startRun(createSave('AIF-C01'),'threshold',five,now)
for (let i=0;i<5;i++) threshold=advanceRun(submitAnswer(setDraft(threshold,i===0?['B']:['A']),now),now)
assert.equal(threshold.activeRun.victory,true,'4/5 is victory')
let ladder=play(createSave('AIF-C01'),[q('ladder')],now)
for (const expected of [1,2,3,4,4]) {
  const due=ladder.reviews.ladder.dueAt
  ladder=play(ladder,[q('ladder')],due)
  assert.equal(ladder.reviews.ladder.stage,expected)
  assert.equal(ladder.reviews.ladder.dueAt,due+[1,3,7,14,30][expected]*DAY)
}
const translated={...q('a'),id:'a-zh',hash:'zh-hash',lang:'zh-TW'}
const beforeTranslate=play(createSave('AIF-C01'),[q('a')],now)
const afterTranslate=play(beforeTranslate,[translated],now+100)
assert.equal(afterTranslate.xp,beforeTranslate.xp,'translation is one reward family')
assert.deepEqual(afterTranslate.reviews,beforeTranslate.reviews)
console.log('RPG engine: rewards, review timing, mastery, four answer types, snapshots, and malformed import guards passed.')
