/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as DiagnosticCodeRouteImport } from './routes/diagnostic.$code'
import { Route as ExamCodeRouteImport } from './routes/exam.$code'
import { Route as PracticeCodeRouteImport } from './routes/practice.$code'
import { Route as RpgCodeRouteImport } from './routes/rpg.$code'
import { Route as StudyCodeRouteImport } from './routes/study.$code'
import { Route as WrongAnswersCodeRouteImport } from './routes/wrong-answers.$code'
import { Route as ExamCodeResultsSessionIdRouteImport } from './routes/exam.$code_.results.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticCodeRoute = DiagnosticCodeRouteImport.update({
  id: '/diagnostic/$code',
  path: '/diagnostic/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCodeRoute = ExamCodeRouteImport.update({
  id: '/exam/$code',
  path: '/exam/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCodeRoute = PracticeCodeRouteImport.update({
  id: '/practice/$code',
  path: '/practice/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RpgCodeRoute = RpgCodeRouteImport.update({
  id: '/rpg/$code',
  path: '/rpg/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCodeRoute = StudyCodeRouteImport.update({
  id: '/study/$code',
  path: '/study/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongAnswersCodeRoute = WrongAnswersCodeRouteImport.update({
  id: '/wrong-answers/$code',
  path: '/wrong-answers/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCodeResultsSessionIdRoute =
  ExamCodeResultsSessionIdRouteImport.update({
    id: '/exam/$code_/results/$sessionId',
    path: '/exam/$code/results/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/diagnostic/$code': typeof DiagnosticCodeRoute
  '/exam/$code': typeof ExamCodeRoute
  '/practice/$code': typeof PracticeCodeRoute
  '/rpg/$code': typeof RpgCodeRoute
  '/study/$code': typeof StudyCodeRoute
  '/wrong-answers/$code': typeof WrongAnswersCodeRoute
  '/exam/$code/results/$sessionId': typeof ExamCodeResultsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/diagnostic/$code': typeof DiagnosticCodeRoute
  '/exam/$code': typeof ExamCodeRoute
  '/practice/$code': typeof PracticeCodeRoute
  '/rpg/$code': typeof RpgCodeRoute
  '/study/$code': typeof StudyCodeRoute
  '/wrong-answers/$code': typeof WrongAnswersCodeRoute
  '/exam/$code/results/$sessionId': typeof ExamCodeResultsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/diagnostic/$code': typeof DiagnosticCodeRoute
  '/exam/$code': typeof ExamCodeRoute
  '/practice/$code': typeof PracticeCodeRoute
  '/rpg/$code': typeof RpgCodeRoute
  '/study/$code': typeof StudyCodeRoute
  '/wrong-answers/$code': typeof WrongAnswersCodeRoute
  '/exam/$code_/results/$sessionId': typeof ExamCodeResultsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/stats'
    | '/diagnostic/$code'
    | '/exam/$code'
    | '/practice/$code'
    | '/rpg/$code'
    | '/study/$code'
    | '/wrong-answers/$code'
    | '/exam/$code/results/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/stats'
    | '/diagnostic/$code'
    | '/exam/$code'
    | '/practice/$code'
    | '/rpg/$code'
    | '/study/$code'
    | '/wrong-answers/$code'
    | '/exam/$code/results/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/stats'
    | '/diagnostic/$code'
    | '/exam/$code'
    | '/practice/$code'
    | '/rpg/$code'
    | '/study/$code'
    | '/wrong-answers/$code'
    | '/exam/$code_/results/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  DiagnosticCodeRoute: typeof DiagnosticCodeRoute
  ExamCodeRoute: typeof ExamCodeRoute
  PracticeCodeRoute: typeof PracticeCodeRoute
  RpgCodeRoute: typeof RpgCodeRoute
  StudyCodeRoute: typeof StudyCodeRoute
  WrongAnswersCodeRoute: typeof WrongAnswersCodeRoute
  ExamCodeResultsSessionIdRoute: typeof ExamCodeResultsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/$code': {
      id: '/diagnostic/$code'
      path: '/diagnostic/$code'
      fullPath: '/diagnostic/$code'
      preLoaderRoute: typeof DiagnosticCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$code': {
      id: '/exam/$code'
      path: '/exam/$code'
      fullPath: '/exam/$code'
      preLoaderRoute: typeof ExamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$code': {
      id: '/practice/$code'
      path: '/practice/$code'
      fullPath: '/practice/$code'
      preLoaderRoute: typeof PracticeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpg/$code': {
      id: '/rpg/$code'
      path: '/rpg/$code'
      fullPath: '/rpg/$code'
      preLoaderRoute: typeof RpgCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$code': {
      id: '/study/$code'
      path: '/study/$code'
      fullPath: '/study/$code'
      preLoaderRoute: typeof StudyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-answers/$code': {
      id: '/wrong-answers/$code'
      path: '/wrong-answers/$code'
      fullPath: '/wrong-answers/$code'
      preLoaderRoute: typeof WrongAnswersCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$code_/results/$sessionId': {
      id: '/exam/$code_/results/$sessionId'
      path: '/exam/$code/results/$sessionId'
      fullPath: '/exam/$code/results/$sessionId'
      preLoaderRoute: typeof ExamCodeResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  DiagnosticCodeRoute: DiagnosticCodeRoute,
  ExamCodeRoute: ExamCodeRoute,
  PracticeCodeRoute: PracticeCodeRoute,
  RpgCodeRoute: RpgCodeRoute,
  StudyCodeRoute: StudyCodeRoute,
  WrongAnswersCodeRoute: WrongAnswersCodeRoute,
  ExamCodeResultsSessionIdRoute: ExamCodeResultsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
