/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticCodeRouteImport } from './routes/diagnostic.$code'
import { Route as ExamCodeRouteImport } from './routes/exam.$code'
import { Route as PracticeCodeRouteImport } from './routes/practice.$code'
import { Route as WrongAnswersCodeRouteImport } from './routes/wrong-answers.$code'
import { Route as ExamCodeResultsSessionIdRouteImport } from './routes/exam.$code_.results.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticCodeRoute = DiagnosticCodeRouteImport.update({
  id: '/diagnostic/$code',
  path: '/diagnostic/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCodeRoute = ExamCodeRouteImport.update({
  id: '/exam/$code',
  path: '/exam/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCodeRoute = PracticeCodeRouteImport.update({
  id: '/practice/$code',
  path: '/practice/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongAnswersCodeRoute = WrongAnswersCodeRouteImport.update({
  id: '/wrong-answers/$code',
  path: '/wrong-answers/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCodeResultsSessionIdRoute =
  ExamCodeResultsSessionIdRouteImport.update({
    id: '/exam/$code_/results/$sessionId',
    path: '/exam/$code/results/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic/$code': typeof DiagnosticCodeRoute
  '/exam/$code': typeof ExamCodeRoute
  '/practice/$code': typeof PracticeCodeRoute
  '/wrong-answers/$code': typeof WrongAnswersCodeRoute
  '/exam/$code/results/$sessionId': typeof ExamCodeResultsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic/$code': typeof DiagnosticCodeRoute
  '/exam/$code': typeof ExamCodeRoute
  '/practice/$code': typeof PracticeCodeRoute
  '/wrong-answers/$code': typeof WrongAnswersCodeRoute
  '/exam/$code/results/$sessionId': typeof ExamCodeResultsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic/$code': typeof DiagnosticCodeRoute
  '/exam/$code': typeof ExamCodeRoute
  '/practice/$code': typeof PracticeCodeRoute
  '/wrong-answers/$code': typeof WrongAnswersCodeRoute
  '/exam/$code_/results/$sessionId': typeof ExamCodeResultsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic/$code'
    | '/exam/$code'
    | '/practice/$code'
    | '/wrong-answers/$code'
    | '/exam/$code/results/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostic/$code'
    | '/exam/$code'
    | '/practice/$code'
    | '/wrong-answers/$code'
    | '/exam/$code/results/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/diagnostic/$code'
    | '/exam/$code'
    | '/practice/$code'
    | '/wrong-answers/$code'
    | '/exam/$code_/results/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticCodeRoute: typeof DiagnosticCodeRoute
  ExamCodeRoute: typeof ExamCodeRoute
  PracticeCodeRoute: typeof PracticeCodeRoute
  WrongAnswersCodeRoute: typeof WrongAnswersCodeRoute
  ExamCodeResultsSessionIdRoute: typeof ExamCodeResultsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/$code': {
      id: '/diagnostic/$code'
      path: '/diagnostic/$code'
      fullPath: '/diagnostic/$code'
      preLoaderRoute: typeof DiagnosticCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$code': {
      id: '/exam/$code'
      path: '/exam/$code'
      fullPath: '/exam/$code'
      preLoaderRoute: typeof ExamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$code': {
      id: '/practice/$code'
      path: '/practice/$code'
      fullPath: '/practice/$code'
      preLoaderRoute: typeof PracticeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-answers/$code': {
      id: '/wrong-answers/$code'
      path: '/wrong-answers/$code'
      fullPath: '/wrong-answers/$code'
      preLoaderRoute: typeof WrongAnswersCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$code_/results/$sessionId': {
      id: '/exam/$code_/results/$sessionId'
      path: '/exam/$code/results/$sessionId'
      fullPath: '/exam/$code/results/$sessionId'
      preLoaderRoute: typeof ExamCodeResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticCodeRoute: DiagnosticCodeRoute,
  ExamCodeRoute: ExamCodeRoute,
  PracticeCodeRoute: PracticeCodeRoute,
  WrongAnswersCodeRoute: WrongAnswersCodeRoute,
  ExamCodeResultsSessionIdRoute: ExamCodeResultsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
